import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import { ScrollArea } from "@/components/ui/scroll-area";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="hidden md:block">
            <Navbar />
            {children} <Toaster richColors />
          </div>
          <div className="grid grid-rows-12 h-screen  md:hidden">
            <ScrollArea className="row-span-11">
              {children} <Toaster richColors />
            </ScrollArea>
            <div className="bg-red-500 row-span-1 py-5 w-full">
              <span>Mobile Menu</span>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
